### ISSUE TITLE
Error when exporting .glb light baked model

### ISSUE THREAD

**Issue by jywarren** [MozillaReality/hubs-blender-exporter#103]
**Description**

I followed the steps in https://hubs.mozilla.com/labs/baked-lighting-for-better-looking-hubs-scenes/ but when I try exporting as a .glb, I see this error. Is there a way to better understand what's causing it? 

**To Reproduce**

See above. Happy to offer more details, it's a complex model, i'm just not sure how to begin debugging myself. Thank you!

**Expected behavior**

I expected a .glb file to be generated. 

**Screenshots**

```
Report: Error
Python: Traceback (most recent call last):
File "/Applications/Blender 3.0.1.app/Contents/Resources/3.0/scripts/addons/io scene gltf2/ init .py", line 637, in execute
return gltf2 blender export.save(context, export settings)
File "/Applications/Blender 3.0.1.app/Contents/Resources/3.0/scripts/addons/io scene gltf2/blender/exp/gltf2 blender export.py", line 46, in save
json, buffer =
export(export settings)
File "/Applications/Blender 3.0.1.app/Contents/Resources/3.0/scripts/addons/io scene gltf2/blender/exp/gltf2 blender export.py", line 71, in export
ison=
fix ison(exporter.q/TF.to dict())
File "/Applications/Blender 3.0.1.app/Contents/Resources/3.0/scripts/addons/io scene gltf2/io/com/gltf2 io.py", line 1203, in to dict
result["materials"] = from union([lambda x: from list(lambda x: to class(Material, x), x), from none],
File "/Applications/Blender 3.0.1.app/Contents/Resources/3.0/scripts/addons/io scene gltf2/io/com/gltf2 io.py", line 56, in from union
assert False
AssertionError
location: <unknown location>:-1
```

**Hardware** 
 - Add-on Release Version: https://github.com/MozillaReality/hubs-blender-exporter/releases/tag/v1_0_0b2
 - Blender Version: 3.0.1 2022-01-26

**Additional context**
*Scene Links, models, any other helpful context*

**Comment by jywarren** [comment]
Aha, using Blender Version 3.2.2 (3.2.2 2022-08-03) resolved the issue. thanks.
