### ISSUE TITLE
Blender 3.2: Video Texture Target fails to export if Custom Properties are included. 

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#80]
**Description**
The video texture target component fails to export from Blender 3.2 when Custom Properties are included in the export.

**To Reproduce**
- Start with Blender's default scene.
- Add a Video Source Component to the camera.
- Add a Video Texture Target component to the default cube's material.
- Set the Video Texture Target's source property to the camera.
- Export to glTF.
- In the exporter window, under the include panel, check the checkboxes for both Custom Properties and Cameras.
- Press 'Export glTF 2.0'.

**Expected behavior**
The export should complete successfully.

**Hardware** 
 - Add-on Release Version: 1.0.0 Beta
 - Blender Version: 3.2.0, 3.2.1

**Additional context**
This appears to be caused by the architecture changes in the glTF exporter for Blender 3.2, during it's material gather it now performs a Python deep copy of the material, and if exporting Custom Properties (gltf_extras) is enabled, the Hubs components will be included as part of that material.  Python's `deepcopy` function doesn't seem to be able to pickle objects of type `bpy.types.Object`, and this causes the error.
<details><summary>Full Python Error</summary>
<pre>
<code>
Python: Traceback (most recent call last):
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/__init__.py", line 628, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "/home/ryan/.config/blender/3.2/scripts/addons/io_hubs_addon/io/gltf_exporter.py", line 55, in patched_gather_gltf
    orig_gather_gltf(exporter, export_settings)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 67, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 35, in gather_node
    mesh=__gather_mesh(vnode, blender_object, export_settings),
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 246, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 61, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 147, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 81, in gather_primitives
    material = gltf2_blender_gather_materials.gather_material(
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 85, in gather_material
    material = deepcopy(base_material)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ryan/Workshop/CustomApps/blender-3.2.1/3.2/python/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'Object' object

</code>
</pre>
</details>

The same issue is present if a bone is used as the source.

**Comment by keianhzo** [comment]
We might be able to (at least temporarily) bypass this un-linking the material component when the node is gathered and restoring it before the material is gathered only for > 3.2 but I'd like to understand better why they introduced this change and look for a more long term sustainable solution. Probably a good topic for discussion in our next dev meeting.
